src/GeoExt/data/reader/WmsDescribeLayer.js
tests/data/reader/WmsDescribeLayer.html

Again we need to guard against multiple `readRecords`-calls and the access of the total property needs to be done with the `getTotal()`-ethod

Fix the tests of the WMSDescribeLayer reader

---

src/GeoExt/tree/LayerNode.js
src/GeoExt/tree/Panel.js
src/GeoExt/tree/Util.js

Bind a checkchange handler for tree nodes for syncing layer visibility and
base layer state. In order to access the handlers they had to be moved to
a new utility file.
With this the 2 tree examples work. Tests will follow.

Make tree compatible to ExtJS 5

---

src/GeoExt/data/LayerModel.js
src/GeoExt/data/reader/Wmc.js
src/GeoExt/data/reader/WmsCapabilities.js

The particular readers are now configured with `preserveRawData: true`.
This PR also again changes the `LayerModel` method `getLayer` and mostly reverts it back to what it was in GeoExt2.0.x.

Fix the tests of the WMSCapabilities and the WMC reader

---

tests/tree/LayerContainer.html

Since the tree package has changed in ExtJS 5 the tests for the GeoExt
tree-LayerContainer class are adapted herewith.
Now they pass with ExtJS 4.2.1 and 5.1.0 (tested in Chromium 39 and FF 34).

Adapt tests for tree/LayerContainer to work w/ ExtJS 4 and 5

---

src/GeoExt/slider/MapPanelItem.js

`panel.map.` would be sometimes `undefined` when testing. This PR suggest being more cautious when trying to get the panel `panel.map.Z_INDEX_BASE.Control`.

Be more cautious when setting zIndex of subitems.

---

src/GeoExt/data/reader/Attribute.js
tests/headless/modules/tawWrapper.js

With this in, we at least can execute more tests on travis unti the CI fails.
It fails at the `protocol.Proxy` tests, which fail for a reason. I doubt that we have finished the work on that class.

Fix travis tests errors partially

---

src/GeoExt/panel/PrintMap.js

When on Windows, the fractional part of a calculated width / height
somehow got stripped away by ExtJS, leading to tiny differences in
the resulting ratio of the print map panel.
When we always round the calculated values, the ratio is fine on all
operating systems.
IE 11 and 9 now is green for me (remember to turn of the compatibility view...)

Round width/height when syncing the size.

---

src/GeoExt/container/VectorLegend.js
tests/panel/Legend.html

A dynamic legend panel will cause an error when a vector layer is added and remove after init of the component. The behavior can be observed via the [online examples](http://geoext.github.io/geoext2/examples/legendpanel/legendpanel.html) feeding the following to the console:
````
mapPanel.layers.add(GeoExt.data.LayerModel.createFromLayer(new OpenLayers.Layer.Vector()));
mapPanel.layers.removeAt(3);
mapPanel.map.zoomOut();
````
This will cause ```Uncaught TypeError: Cannot read property 'map' of null``` by calling the ```VectorLegend:onMapZoom``` event handler of the disposed vector legend.
To fix this the cached map property of the legend is used to unbind all event handlers.

Prevent leaking event bindings of dynamic legend panels. 

---

examples/tree/tree.js
resources/css/tree-access.css
resources/css/tree-classic.css
resources/css/tree-gray.css
resources/css/tree-neptune.css
src/GeoExt/data/LayerTreeModel.js
src/GeoExt/tree/LayerNode.js
src/GeoExt/tree/View.js

I would like to add some visual feedback for layers that are scale-based and move out of range of the maps resolution. It may be worthwhile to have in the base library as well.
This is a first draft which makes sure active layers that become non-visible to resolution constraints are unchecked and vice-versa. I'm unsure if this is the most user friendly approach though.

Add visual feedback of layers out of range to tree panel

---

README.md

The script-tag for the loader.js is not necessary for this minimal example and creates a HTTP 404 since this script only exists in the project's example folder.

Correct minimal app example in README

---

.sencha/package/sencha.cfg
guides/single_file_build/README.md
package.json

This PR aims to be less intrusive than #302 while still adding support for Sencha CMD. It only adds one configuration file and some docs (which may be extended in the future).
To play nice with Cmd the following changes had to be made to the newly added package.json:
- Cmd only allows numeric version so I dropped the `-dev` suffix
- `type` needs to be set to code
- `compatVersion` will probably be helpful with upgrading to future versions
I tried it with an existing application (ExtJS 4.2.1) as well as with a newly generated test app (ExtJS 5.1).

Adopt minimal Sencha Cmd package requirements

---

src/GeoExt/data/reader/WmsDescribeLayer.js

Same className is used by `GeoExt.data.reader.WMSCapabilities'.

Fix accidental overwrite of alternateClassName of WMSCapabilitiesReader.

---

examples/printform/print-form.js
src/GeoExt/data/MapfishPrintProvider.js
src/GeoExt/plugins/PrintProviderField.js
tests/data/MapfishPrintProvider.html

I have the requirement to "print" other formats than pdf via Geoserver printing and thought this may be interesting for upstream as well.
Right now I have problems to configure Geoserver printing to work with other formats than PDF so this has not been tested "live" but only via programmatic tests. I also changed the print-form example to include the outputFormat option but the hosted printing service also fails on delivering the supported formats (as of info.json it should deal with PNG for example).
````
Error while generating PDF:
java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/convert": error=2, Datei oder Verzeichnis nicht gefunden
at org.mapfish.print.output.NativeProcessOutputFactory$ImageOutput.print(NativeProcessOutputFactory.java:202)
at …
```

Add outputFormat as a none-custom param of MapfishPrintProvider

---

README.md

This changes the README file so the compatibility to ExtJS 5 is shown,
which will be introduced by version 2.1.x.

Adapt README for Version 2.1.x

---

src/GeoExt/tree/LayerNode.js

I think there are some dangling event listeners associated with the layer node. I hope to fix this with this PR.
As far as I can tell, there is no reasonable way to hook into the destruction of the LayerTreeModel of the LayerNode to fix this so I used the maps 'removelayer' event. 'preremovelayer' is not an option as other listeners outside of this scope may cancel removing the layer. That's also the reason for caching a reference to the actual map. When 'removelayer' is called the layers map property is already lost.

Dispose layer tree node event listeners.

---

src/GeoExt/plugins/PrintProviderField.js
tests/plugins/PrintProviderField.html

With associated test. See issue #363

Fix PrintProviderField to work with textboxes

---

package.json
src/GeoExt/Version.js

For the next beta release (2.1.0-beta.2) the version number declarations
have to be adapted.

Set version numbers to 2.1.0-beta.2

---

package.json
src/GeoExt/Version.js

After the 2.1.0-beta.2 version has been released, the version
declarations are set back to 2.1.0-dev.

Set versions back to 2.1.0-dev

---

src/GeoExt/tree/Util.js

When the map panel is loaded in an initially hidden ExtJS tab, the owner tree is not yet rendered, so call to "node.getOwnerTree()" returns undefined.  This caused an error message when trying to call
"node.getOwnerTree().getChecked()".

Fix JavaScript error when the map panel is loaded in a hidden ExtJS tab

---

src/GeoExt/tree/LayerNode.js

When the map panel is loaded in an initially hidden ExtJS tab, the
owner tree is not yet rendered, so call to "node.getOwnerTree()"
returns undefined.  This caused an error message when trying to call
"node.getOwnerTree().getChecked()".
Backported from 5cb2864198b8901c6ca0af01f59c35f02ed438da
See also #367
Cheers for any review.

Fix JavaScript error when the map panel is loaded in a hidden  ExtJS tab

---

package.json
src/GeoExt/Version.js

For the next beta release (2.1.0-beta.3) the version number declarations
are adapted herewith.
The new beta seems to be necessary since a bug has been fixed by #367.

Set version numbers to 2.1.0-beta.3

---

src/GeoExt/tree/Util.js

Hi devs,
I would suggest to add an additional check in class ```GeoExt.tree.Util.js``` to ensure if a tree node really has a property 'layer' before its visibility is updated.
This mini check could be useful for applications, that use complex layer trees with nested folder structures (e.g. layer folder has checkboxes to check/uncheck all layers inside). In this case the folder itself has obviously no corresponding layer.
See also PR #355, especially df4ec85 - it handles the same issue, just solved in a bit other way ;)

Add additional check whether the tree node has a 'layer' property

---

package.json

Removes the `-dev` suffix from version and adds attribute `namespace` which is created by the Sencha Cmd tool upgrading the package. As all components reside in that namespace anyway, this should be good to go.

Update package.json for compat with Sencha tools

---

src/GeoExt/tree/Panel.js

This avoids 10000px wide colums in the TreePanel when working with ExtJS 5.
This happened because the ``Ext.isIE6`` flag is gone in ExtJS 5, what always activated the IE6 workaround with setting the column width to 10000px. Since we do not support IE 6 I removed the ternary operator by setting the width to ``100%`` which works for ExtJS 4 and 5.

Avoid too wide colums in TreePanel (ExtJS 5)

---

src/GeoExt/data/reader/Feature.js
src/GeoExt/form/action/Search.js
src/GeoExt/selection/FeatureModel.js

Fixes #146. Old aliases haven't been removed for backwards compatibility.

Prefix GeoExt components with "gx_"

---

src/GeoExt/data/proxy/Protocol.js
tests/busstops.geojson
tests/data/proxy/Protocol.html

This PR is supposed to fix the FeatureStore issues (ExtJS 5) documented in #378.
As discussed in #378 this fixes issue 1.) and can be used as base for further development to fix issue 2.)

Prevent inadvertently repeated callbacks in ProtocolProxy

---

src/GeoExt/data/LayerTreeModel.js

This is a small PR to fix the wrong defined defaultValue for the disabled field in the LayerTreeModel.

Fixes wrong defined defaultValue for "disabled".
